name: sensor_picker
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  battery_info: ^1.1.1
  flutter:
    sdk: flutter
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null
